### ISSUE TITLE
requirejs

### ISSUE THREAD

**Issue by light9** [mominsamir/date-time-picker#5]
Thank you for this nice module. Can you please advice how to use it with require.js. In my case console always show:
 "Module 'dateTimePicker' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."
I checked all paths and it correct.

```
paths: {
    ...
    'angular-material': '../bower_components/angular-material/angular-material',
    'moment': '../bower_components/moment/min/moment-with-locales.min',
    'datepicker': '../bower_components/smDateTimeRangePicker/dist/sm-picker-min'                                                                                                                                                                         
},

// Add angular modules that does not support AMD out of the box, put it in a shim
shim: {
  'angular-material':['angular','angular-animate','angular-aria'],
  'datepicker': ['angular', 'moment']                                                                   
}
```

...
define([
'angularAMD',
'angular-material',
'moment',
'datepicker',
], function (angularAMD) {
var app = angular.module("app", ['ngMaterial', 'smDateTimeRangePicker']);
    return angularAMD.bootstrap(app);
});

**Comment by mominsamir** [comment]
Hi I think its fixed now, i just pushed new commit with version 0.0.7b,

Problem was not with your code but my source code, yesterday i committed incorrect files.

http://plnkr.co/edit/2ePb5nf8vH71iH5byP7q?p=preview

close the issue if this fix works for you.

**Comment by light9** [comment]
Thanks! It works now, but I dont understand, how to define moment in my case.
I receive: "ReferenceError: moment is not defined". Can you advice, please, how to add moment in my requirejs configuration?
where i should add 
var moment = require('moment');
?

**Comment by mominsamir** [comment]
I have never worked with  requirejs. Please follow the documentation from momentjs.

http://momentjs.com/docs/#/use-it/require-js/

this should help you out.

**Comment by light9** [comment]
Got it. Just added:

var moment = require('moment');

at the top of sm-picker-min.js

'use strict';
var moment = require('moment');
function run($templateCache){........

Thank you again for your great work. I guess its the best datetimepicker for angular material.
